#!/bin/sh
# Generated device setup for RAUC. Runs BEFORE rauc.service.
# @RAUC_SYSTEM_COMPATIBLE@ / @RAUC_BUNDLE_FORMATS@ are sed-replaced at build time.
set -e

# 1. Boot device from /proc/cmdline, strip partition suffix to get the base device.
#    TI J722S: p1=boot(FAT), p2=rootfs0, p3=rootfs1, p4=data.
#    NOTE (TI-specific, opposite of NXP): mmcblk0=eMMC, mmcblk1=SD.
ROOT_DEV=$(grep -oE 'root=/dev/[a-z0-9]+' /proc/cmdline | head -n1 | sed 's#root=/dev/##; s/p[0-9]*$//')

case "${ROOT_DEV}" in
    mmcblk0)
        BOOT_DEV=/dev/mmcblk0p1
        SLOT0_DEV=/dev/mmcblk0p2
        SLOT1_DEV=/dev/mmcblk0p3
        DATA_DEV=/dev/mmcblk0p4
        ;;
    mmcblk1)
        BOOT_DEV=/dev/mmcblk1p1
        SLOT0_DEV=/dev/mmcblk1p2
        SLOT1_DEV=/dev/mmcblk1p3
        DATA_DEV=/dev/mmcblk1p4
        ;;
    *)
        echo "rauc-setup-env: unknown boot device '${ROOT_DEV}'" >&2
        exit 1
        ;;
esac

# 2. Mount persistent /data (p4) BEFORE rauc reads system.conf (statusfile/data-directory live here).
mkdir -p /data
mountpoint -q /data || mount -t ext4 "${DATA_DEV}" /data
mkdir -p /data/rauc

# 3. Generate /etc/fw_env.config. TI stores U-Boot env as a FAT file (uboot.env), not a raw offset.
BOOT_MNT=$(lsblk -no MOUNTPOINT "${BOOT_DEV}" | head -n1)
if [ -z "${BOOT_MNT}" ]; then
    mkdir -p /run/boot
    mount "${BOOT_DEV}" /run/boot
    BOOT_MNT=/run/boot
fi
cat > /etc/fw_env.config <<EOF
# Auto-generated by rauc-setup-env.service
# Device                Offset   Env size
${BOOT_MNT}/uboot.env   0x0      0x40000
EOF

# 4. Generate /etc/rauc/system.conf.
cat > /etc/rauc/system.conf <<EOF
# Auto-generated by rauc-setup-env.service
[system]
compatible=@RAUC_SYSTEM_COMPATIBLE@
bootloader=uboot
bundle-formats=@RAUC_BUNDLE_FORMATS@
statusfile=/data/rauc.status
data-directory=/data/rauc

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=${SLOT0_DEV}
type=ext4
bootname=system0

[slot.rootfs.1]
device=${SLOT1_DEV}
type=ext4
bootname=system1
EOF

# 5. Debug marker.
touch /data/.rauc-env-configured